import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { File, Paths } from "expo-file-system";

import { PRODUCT, SCHOOL } from "@/src/constants/branding";

function csvCell(v: string): string {
  const needsQuote = /[",\n]/.test(v);
  const escaped = v.replace(/"/g, '""');
  return needsQuote ? `"${escaped}"` : escaped;
}

export async function shareCsv(
  baseName: string,
  columns: string[],
  rows: string[][],
): Promise<{ ok: boolean; reason?: string }> {
  try {
    const lines = [columns, ...rows].map((r) => r.map(csvCell).join(","));
    const csv = lines.join("\n");
    const file = new File(Paths.cache, `${baseName}-${Date.now()}.csv`);
    file.create({ overwrite: true });
    file.write(csv);
    if (!(await Sharing.isAvailableAsync())) {
      return { ok: false, reason: "unavailable" };
    }
    await Sharing.shareAsync(file.uri, {
      mimeType: "text/csv",
      dialogTitle: "Export CSV",
      UTI: "public.comma-separated-values-text",
    });
    return { ok: true };
  } catch (e) {
    return { ok: false, reason: String(e) };
  }
}

export function buildReportHtml(opts: {
  title: string;
  subtitle?: string;
  summary?: { label: string; value: string }[];
  columns: string[];
  rows: string[][];
}): string {
  const summaryHtml = (opts.summary ?? [])
    .map(
      (s) =>
        `<div class="kpi"><div class="kpi-label">${s.label}</div><div class="kpi-value">${s.value}</div></div>`,
    )
    .join("");
  const head = opts.columns.map((c) => `<th>${c}</th>`).join("");
  const body = opts.rows
    .map((r) => `<tr>${r.map((c) => `<td>${c}</td>`).join("")}</tr>`)
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"/>
  <style>
    body{font-family:-apple-system,Helvetica,Arial,sans-serif;color:#111827;padding:28px;}
    .brand{font-size:20px;font-weight:800;color:#0F172A;}
    .muted{color:#6B7280;font-size:12px;}
    h1{font-size:18px;margin:16px 0 2px;}
    .kpis{display:flex;flex-wrap:wrap;gap:10px;margin:14px 0;}
    .kpi{border:1px solid #E5E7EB;border-radius:10px;padding:10px 14px;min-width:120px;}
    .kpi-label{font-size:11px;color:#6B7280;font-weight:600;}
    .kpi-value{font-size:16px;font-weight:800;color:#1E3A8A;}
    table{width:100%;border-collapse:collapse;margin-top:10px;font-size:12px;}
    th{background:#1E3A8A;color:#fff;text-align:left;padding:8px;}
    td{padding:7px 8px;border-bottom:1px solid #EEF;}
    tr:nth-child(even) td{background:#F9FAFB;}
    .head{border-bottom:2px solid #1E3A8A;padding-bottom:12px;}
    .foot{margin-top:22px;color:#9CA3AF;font-size:10px;text-align:center;}
    .demo{display:inline-block;background:#FFFBEB;color:#B45309;font-weight:800;font-size:10px;padding:3px 8px;border-radius:5px;margin-left:8px;}
  </style></head><body>
    <div class="head">
      <span class="brand">${PRODUCT.trademark}</span><span class="demo">DEMO REPORT</span>
      <div class="muted">${SCHOOL.name} &middot; ${SCHOOL.location} &middot; Session ${SCHOOL.session}</div>
    </div>
    <h1>${opts.title}</h1>
    ${opts.subtitle ? `<div class="muted">${opts.subtitle}</div>` : ""}
    <div class="kpis">${summaryHtml}</div>
    <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>
    <div class="foot">Generated by ${PRODUCT.trademark} &middot; System-generated demo report.</div>
  </body></html>`;
}

export async function sharePdf(
  html: string,
): Promise<{ ok: boolean; reason?: string }> {
  try {
    const { uri } = await Print.printToFileAsync({ html });
    if (!(await Sharing.isAvailableAsync())) {
      return { ok: false, reason: "unavailable" };
    }
    await Sharing.shareAsync(uri, {
      mimeType: "application/pdf",
      dialogTitle: "Export PDF",
    });
    return { ok: true };
  } catch (e) {
    return { ok: false, reason: String(e) };
  }
}
